version: '3.8'

services:
  backend:
    build: .
    container_name: auth-backend
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/Users
      - JWT_SECRET=CTSEOiiiii
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
