version: '3.8'

services:
  backend:
    build: .
    container_name: auth-service
    ports:
      - '5001:5001'
    environment:
      - PORT=5001
      - MONGO_URI=mongodb+srv://thisaraganhewa1:thisara1@cluster0.kbxsy08.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=CTSEOiiiii
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
